

CREATE_USER_AUTH_TABLE = """
CREATE TABLE IF NOT EXISTS USER_AUTH (
	username    TEXT NOT NULL,
    password    TEXT NOT NULL
);
"""


CREATE_MEMBER_TABLE = """
CREATE TABLE IF NOT EXISTS MEMBER (
	id	INTEGER NOT NULL PRIMARY KEY,
	name	TEXT,
	surname	TEXT,
 	birthdate TEXT,
	phone	REAL,
    adress TEXT,
    email TEXT,
    category TEXT,
    username TEXT NOT NULL UNIQUE
);
"""

CREATE_PLAYER_TABLE = """
CREATE TABLE IF NOT EXISTS PLAYER (
	memberID	INTEGER NOT NULL
);
"""

CREATE_COACH_TABLE = """
CREATE TABLE IF NOT EXISTS COACH (
	memberID	INTEGER NOT NULL	
);
"""

CREATE_TOURNAMENT_TABLE = """
CREATE TABLE IF NOT EXISTS TOURNAMENT (
	id	INTEGER NOT NULL PRIMARY KEY,
    deadline TEXT,
    fee REAL,
    prize REAL,
    date TEXT,
    sTime TEXT
);
"""

CREATE_TOURNAMENT_PARTICIPATION_TABLE = """
CREATE TABLE IF NOT EXISTS TOURNAMENT_PARTICIPATION (
	playerID	INTEGER NOT NULL,
    tournamentID	INTEGER NOT NULL,
    PRIMARY KEY (playerID, tournamentID)
);
"""

CREATE_SUBSCRIPTION_TABLE = """
CREATE TABLE IF NOT EXISTS SUBSCRIPTION (
	id	INTEGER NOT NULL PRIMARY KEY,
    startDate TEXT,
    endDate TEXT,
    type TEXT,
    category TEXT,
    status TEXT
);
"""

CREATE_PLAYER_SUBSCRIPTION_TABLE = """
CREATE TABLE IF NOT EXISTS PLAYER_SUBSCRIPTION (
    playerID INTEGER NOT NULL,
    subscriptionID INTEGER NOT NULL,
    PRIMARY KEY (playerID, subscriptionID)
);
"""

CREATE_EQUIPMENT_TABLE = """
CREATE TABLE IF NOT EXISTS EQUIPMENT (
	id	INTEGER NOT NULL PRIMARY KEY,
    description TEXT,
    characteristicCode TEXT,
    availability TEXT
);
"""
CREATE_EQUIPMENT_RENTAL_TABLE = """
CREATE TABLE IF NOT EXISTS EQUIPMENT_RENTAL (
    playerID INTEGER NOT NULL,
    equipmentID INTEGER NOT NULL,
    rentDate TEXT,
    PRIMARY KEY (playerID, equipmentID)
);
"""

CREATE_LESSON_TABLE = """
CREATE TABLE IF NOT EXISTS LESSON (
	id	INTEGER NOT NULL PRIMARY KEY,
    date TEXT,
    startTime TEXT,
    endTime TEXT,
    difficulty TEXT,
    coachID INTEGER
);
"""

CREATE_LESSON_PARTICIPATION_TABLE = """
CREATE TABLE IF NOT EXISTS LESSON_PARTICIPATION (
	playerID	INTEGER NOT NULL,
    lessonID	INTEGER NOT NULL,
    PRIMARY KEY (playerID, lessonID)
);
"""

CREATE_RESERVATION_TABLE = """
CREATE TABLE IF NOT EXISTS RESERVATION (
	id	INTEGER NOT NULL PRIMARY KEY,
    fieldID INTEGER,
    startTime TEXT,
    endTime TEXT,
    lessonID INTEGER,
    coachID INTEGER
);
"""

CREATE_PLAYER_RESERVATION_TABLE = """
CREATE TABLE IF NOT EXISTS PLAYER_RESERVATION (
	playerID	INTEGER NOT NULL,
    reservationID	INTEGER NOT NULL,
    PRIMARY KEY (playerID, reservationID)
);
"""


CREATE_FIELD_TABLE = """
CREATE TABLE IF NOT EXISTS FIELD (
    id INTEGER NOT NULL PRIMARY KEY,
    type TEXT,
    status TEXT
);
"""

CREATE_FIELD_RESERVATION_TABLE = """
CREATE TABLE IF NOT EXISTS FIELD_RESERVATION (
	reservationID	INTEGER NOT NULL,
    fieldID	INTEGER NOT NULL,
    PRIMARY KEY (reservationID, fieldID)
);
"""