SELECT_PLAYER_ID_FROM_USERNAME = "SELECT id FROM MEMBER WHERE username = (?)"
SELECT_COACH_ID_FROM_USERNAME = "SELECT id FROM MEMBER WHERE username = (?)"
SELECT_USERNAME_FROM_USER_AUTH = "SELECT username FROM USER_AUTH WHERE username = (?)"
SELECT_PASSWORD_FROM_USER_AUTH = "SELECT password FROM USER_AUTH WHERE username = (?)"