UPDATE_RESERVATION = "UPDATE RESERVATION SET coachid = (?) WHERE id = (?)"
UPDATE_EQUIPMENT_STATUS = "UPDATE EQUIPMENT SET availability = (?) WHERE id = (?)"
UPDATE_SUBSCRIPTION_STATUS = "UPDATE SUBSCRIPTION SET status = 'Inactive' WHERE playerID = (?)"